### ISSUE TITLE
Update to latest

### ISSUE THREAD

**Issue by ychaker** [glassechidna/zxing_cpp.rb#2]
Hello,
I don't know if you are still maintaining this repo, but it seems that your original cpp repo (https://github.com/glassechidna/zxing-cpp) is being maintained and updated.

I was wondering if you will update this repo, if not, could you guide me how to integrate the latest version of the cpp repo?

Thanks

**Comment by Benjamin-Dobell** [comment]
I've published a 0.1.1 release to RubyGems for you:

https://rubygems.org/gems/zxing_cpp

**Comment by Benjamin-Dobell** [comment]
For future reference, if you (or anyone else for that matter) ever does get stuck waiting for me. If you're using bundler then you can:
1. Fork this repo.
2. Clone your fork onto your computer:
   
   ```
   git clone https://github.com/<YOUR_USERNAME>/zxing_cpp.rb.git
   cd zxing_cpp.rb
   git submodule update --init --recursive
   ```
3. Update the zxing-cpp submodule:
   
   ```
   cd ext/zxing/zxing-cpp
   git pull
   cd ../../..
   git add --update
   git commit -m "Updated zxing-cpp version"
   git push
   ```
4. In your project using zxing_cpp.rb, in your Gemfile specify your `zxing_cpp` dependency as:
   
   ```
   gem 'zxing_cpp', git: 'https://github.com/<YOUR_USERNAME>/zxing_cpp.rb.git'
   ```
5. Update your `Gemfile.lock`
   
   ```
   bundle update zxing_cpp
   ```

Of course, you're still welcome to prompt me to do an update. It's just nice to know you're not 100% stuck relying on someone else.

**Comment by ychaker** [comment]
Awesome. 
This is wonderful, the set by step guide of how to update is just brilliant. 
Thank you for this. 

🎉 🎉 🎉 🎉 🎉
