### ISSUE TITLE
pdf417 support

### ISSUE THREAD

**Issue by ychaker** [glassechidna/zxing_cpp.rb#3]
Hi again,
I asked about updating the gem with the latest from the cpp repo thinking that it has the latest support for pdf417 barcodes since the directory exists: https://github.com/glassechidna/zxing-cpp/tree/master/core/src/zxing/pdf417

But it seems that it's not working properly. 
If I download the ZXing jar for 3.2.0 and run it against the same image as I am using this gem, the jar would parse it properly and return the expect result, whereas the gem returns `nil`. 

I'm not doing anything fancy just running `ZXing.decode path` against a local image of the back of a driver's license. 

Any ideas why I'm seeing different results? 
I'd like to avoid using the jars if possible.

Thanks again.

**Comment by Benjamin-Dobell** [comment]
This gem uses `MultiFormatReader` from zxing-cpp. `MultiFormatReader` does incorporate `PDF417Reader`; so my guess is a bug in either `MultiFormatReader` or `PDF417Reader` within zxing-cpp itself (not this gem). 

I'd suggest opening an issue against https://github.com/glassechidna/zxing-cpp itself, to track the issue.

However, zxing-cpp is very much out of sync with the Java ZXing code-base. At the time of zxing-cpp's inception it was forked from an already out-of-date (unsupported) C++ port of ZXing, that was previously maintained as part of the official ZXing project. Support was dropped by the official team, hence the fork.

Unfortunately zxing-cpp doesn't really have any active developers. It's just _barely_ maintained by myself purely as a place for the community to share their contributions.

As such, to get this working I suspect you'll need to investigate yourself. I'd suggest setting up a C++ project using zxing-cpp, feed your image into both `MultiFormatReader` and `PDF417Reader`, and try debug the issue. Pull requests are definitely welcome!

**Comment by ychaker** [comment]
Thank you for the feedback.
I haven't done any C++ since college, and my knowledge is very limited. 
Plus, the client will not pay for me to spend time debugging this issue (I wish they would), because they already had a plan to use a paid service and I convinced them to let me try using this gem first. 
If, in the long run, they decide it's worth the time to spend getting it to work vs paying for a third party service then I'd be happy to take a shot at a pull request. 

I appreciate your support and your quick response! 
Keep up the good work :)
