### ISSUE TITLE
cmake error when installing via git

### ISSUE THREAD

**Issue by philister** [glassechidna/zxing_cpp.rb#4]
Hi,
when I try to install the gem via Gemfile: `gem 'zxing_cpp', git: 'git://github.com/glassechidna/zxing_cpp.rb.git' `, I get this error:
```
CMake Error: The source directory "bundler/gems/zxing_cpp.rb-87f525035e63/ext/zxing/zxing-cpp" does not appear to contain CMakeLists.txt
```

Any ideas?

I try to enable the QRCodeMultiReader, but I already fail to run it from a ocal path.

Thanks and regards, Phil

**Comment by Benjamin-Dobell** [comment]
The native C++ library is referenced as a submodule, so you need to use:

```ruby
gem 'zxing_cpp', git: 'https://github.com/glassechidna/zxing_cpp.rb.git', submodules: true
```

**Comment by Benjamin-Dobell** [comment]
If you're trying to make local modifications you'll also need to pull down the submodules i.e.

```
git clone https://github.com/glassechidna/zxing_cpp.rb.git
cd zxing_cpp.rb
git submodule update --init --recursive
```

**EDIT:** There's presently actually only one submodule, and no recursive submodules calling `git submodule` recursively is just good practice.

**Comment by philister** [comment]
Thanks for your help! That worked.
